### ISSUE TITLE
tab & folded content

### ISSUE THREAD

**Issue by salander0411** [aws-samples/aws-alexa-workshop#3]
(1) tab anchor direct in 7.create lambda  fails.. don't know how to solve this

If you are familiar with [Serverless Framework](https://serverless.com/), you can 
go direct to [Option 2: Deploy via Serverless Framework]({{< relref "#deploy-via-serverless-framework" >}})

(2) suggest add folded function for challenge part.

**Comment by JoeShi** [comment]
@salander0411 it there still a problem?

**Comment by salander0411** [comment]
removing the folded part. close the issue.
