### ISSUE TITLE
S3 error: the specified key does not exist

### ISSUE THREAD

**Issue by JoeShi** [aws-samples/aws-alexa-workshop#6]
Lab1, Step 5

<img width="991" alt="WechatIMG1 1" src="https://user-images.githubusercontent.com/2173635/67222573-29647d00-f460-11e9-9246-56ac41d1bc16.png">

**Comment by salander0411** [comment]
This is not a bug.  You cannot change the 'BootstrapBucket' (aws-bigdata-blog)  and 'BootstrapPrefix' (artifacts/aws-lex-web-ui/artifacts) because that's where the origin codes exist. Just follow the guide and DO NOT change everything that the guide don't ask you to change.
